# Generated by Django 2.2.3 on 2019-07-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_features_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfoliophoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfoliophoto')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
    ]
