# Generated by Django 2.2.3 on 2019-07-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20190731_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('icontitle', models.CharField(max_length=255)),
                ('icondescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='features',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='features',
            name='icondescription',
        ),
        migrations.RemoveField(
            model_name='features',
            name='icontitle',
        ),
    ]
