# Generated by Django 2.2.3 on 2019-07-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_auto_20190731_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='description',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
