# Generated by Django 2.2.3 on 2019-07-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_footerfields_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerfields',
            name='url',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
