# Generated by Django 2.2.3 on 2019-07-31 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_footerfields_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerfields',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='footerfields',
            name='url',
        ),
        migrations.CreateModel(
            name='Footermenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.Footerfields')),
            ],
        ),
    ]
