# Generated by Django 2.2.3 on 2019-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0012_auto_20190731_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='footericon',
            name='url',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
