# Generated by Django 2.2.3 on 2019-08-02 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0016_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Fullname', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Headline', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('description_new', models.CharField(max_length=255)),
                ('Profilephoto', models.ImageField(upload_to='profilephoto')),
                ('Backgroundphoto', models.ImageField(upload_to='backgroundphoto')),
                ('Username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
