# Generated by Django 2.2.3 on 2019-08-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0017_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Fullname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Backgroundphoto',
            field=models.ImageField(blank=True, null=True, upload_to='backgroundphoto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profilephoto',
            field=models.ImageField(blank=True, null=True, upload_to='profilephoto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description_new',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
