# Generated by Django 2.2.3 on 2019-08-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0018_auto_20190802_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
