# Generated by Django 2.2.3 on 2019-08-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0019_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
