# Generated by Django 2.2.3 on 2019-08-05 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0021_auto_20190805_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='SettingsProfile',
        ),
    ]
