# Generated by Django 2.2.3 on 2019-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0023_auto_20190805_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description_new',
            new_name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
