# Generated by Django 2.2.3 on 2019-08-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0024_auto_20190805_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
