# Generated by Django 2.2.3 on 2019-08-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0026_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
