# Generated by Django 2.2.3 on 2019-08-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0034_post_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
