# Generated by Django 2.2.3 on 2019-08-13 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0037_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View',
        ),
    ]
