# Generated by Django 2.2.3 on 2019-08-15 12:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0043_auto_20190815_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_setting',
            new_name='Socialsetting',
        ),
    ]
