# Generated by Django 2.2.3 on 2019-08-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0044_auto_20190815_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profileicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
