# Generated by Django 2.2.3 on 2019-08-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0045_profileicon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
