# Generated by Django 2.2.3 on 2019-08-23 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0047_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='JQVhLA2CnEjoAlmFn5cQy7sMkcZdDd6IFXRODNKsYACnPhi047GmJznG1jiLesvwp0QyFKov9S6SRReuydWSRzT2a7kSQKgRJ4eX40zpqtNordxIJDEMrt87', max_length=120)),
                ('expire', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
