# Generated by Django 2.2.3 on 2019-08-23 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0048_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forget_Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='6IuigKTfoOHUOQ5YAJSuiUUYkpfAlPFRb02urNaENVMGJgYxrctACf3fTSuHcV5kikNP7nB2J52eUMbCkUjAqxFSgwH0UZfFmfzWUmmpjXDSRXRpBIGYcBnn', max_length=120)),
                ('expire', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
