# Generated by Django 2.2.3 on 2019-08-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0049_auto_20190823_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Forget_Password',
        ),
    ]
