# Generated by Django 2.2.3 on 2019-08-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0050_auto_20190831_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=220)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
    ]
