# Generated by Django 2.2.3 on 2019-08-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0052_auto_20190831_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='descmail',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='iconmail',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
