# Generated by Django 2.2.3 on 2019-08-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='backgroundphoto',
            field=models.ImageField(blank=True, unique=True, upload_to='', verbose_name='backgroundphoto'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.TextField(blank=True, unique=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='headline',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='headline'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='location',
            field=models.CharField(blank=True, max_length=150, verbose_name=' location'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profilephoto',
            field=models.ImageField(blank=True, unique=True, upload_to='', verbose_name='profilephoto'),
        ),
    ]
