# Generated by Django 2.2.3 on 2019-08-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20190806_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='backgroundphoto',
            field=models.ImageField(blank=True, upload_to='', verbose_name='backgroundphoto'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='headline',
            field=models.EmailField(blank=True, max_length=254, verbose_name='headline'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profilephoto',
            field=models.ImageField(blank=True, upload_to='', verbose_name='profilephoto'),
        ),
    ]
