# Generated by Django 2.2.3 on 2019-08-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_auto_20190806_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='headline',
            field=models.TextField(blank=True, verbose_name='headline'),
        ),
    ]
