# Generated by Django 2.2.3 on 2019-08-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_auto_20190806_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profilephoto',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='', verbose_name='profilephoto'),
        ),
    ]
